//=============================CONSTANTS

var BUTTON_PADDING_V = 10;
var BUTTON_PADDING_H = 10;

//var ANNOTATION_WIDTH = 600;
var ANNOTATION_WIDTH = 200;
var ANNOTATION_HEIGHT = 100;

var LANGUAGE_PADDING_H = 150;

var CREDITS_WIDTH = 700;

var PADDING_V = 70;
var PADDING_V_MEMORY = 7;
var PADDING_V_AUDIO = 14;
var PADDING_H = 7;
var LEVEL_PADDING_H = 55;

//var CARD_WIDTH = 280;
var CARD_WIDTH = 170;
//var CARD_HEIGHT = 203;
//var CARD_HEIGHT = 102;
var CARD_HEIGHT = 123;
var BUTTON_WIDTH = 300; 
var BUTTON_HEIGHT = 80; 


var START_BUTTON_WIDTH = 100; 
var START_BUTTON_HEIGHT = 30; 



var LABEL_WIDTH = 210;
var LABEL_HEIGHT = 30;

var LEVEL_BUTTON_WIDTH = 200;

var OFFSET = 2;

var TOP_OFFSET = 220;
var TOP_OFFSET_MEMORY = 250;

var CARD_AUDIO_LABEL_OFFSET = 35;


//248
var LEFT_OFFSET_ALL_ELEMENTS = 7;
var MAX_WIDTH_ELEMENTS = 700;
var MAX_WIDTH_PARAMS = 600;

var MAX_MENU_HEIGHT = 452;
var MAX_MENU_WIDTH = 640;
var MAX_LANG_MENU_WIDTH = 640;

//var MAX_DESC_WIDTH = 635;
var MAX_DESC_WIDTH = 660;
var MAX_DESC_HEIGHT = 90;



var INNER_DELIMITER = "#";

var GAME_SELECTOR_WIDTH = 230;


var FILTER_OFFSET = 90;
var OFFSET_CENTER = 63;
var OFFSET_PIC_WORDS = 50;


var LABEL_OFFSET = 17;


var BORDER_WIDTH = 1.5;

var DOWNLOAD_OFFSET = 67;

